# fly.toml app configuration file generated for super-cronic-test on 2024-08-23T12:49:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'super-cronic-test'
primary_region = 'lax'

[build]

[processes]
  cron = 'supercronic ./crontab'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['cron']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
